MODEL:
  TYPE: darswin_az
  NAME: grp1
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: /home/prongs/scratch/DarSwin_g_theta/gp1/ckpt_epoch_270.pth
  SWIN:
    DISTORTION : 'spherical'
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 4
    N_RADIUS : 25
    N_AZIMUTH : 4
    RADIUS_CUTS : 16
    AZIMUTH_CUTS : 64

  SWINAZ:
    WINDOW_SIZE: (1,16)

DATA:
  IMG_SIZE: 64
  BATCH_SIZE: 16
  MAX_DEPTH: 8.0

TEST:
  CKPT: '/home/prongs/scratch/darswin_g_theta/grp2/epoch_445.pth'