MODEL:
  TYPE: darswin_az
  NAME: dar_10_10
  NUM_CLASSES : 1000
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: /home-local2/icshi.extra.nobkp/CKPT/last_pe/dar_64_10_gp4/ckpt_epoch_325.pth
  SWIN:
    DISTORTION : 'spherical'
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 4
    N_RADIUS : 10
    N_AZIMUTH : 10
    RADIUS_CUTS : 16
    AZIMUTH_CUTS : 64

  SWINAZ:
    WINDOW_SIZE: (1,16)

DATA:
  IMG_SIZE: 64
  BATCH_SIZE: 16

TEST:
  CKPT: '/home-local2/icshi.extra.nobkp/experiments/dar_gp4_175_aug_mask_2/epoch_499.pth'