MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window4_64
  DROP_PATH_RATE: 0.2
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 4
  SWINAZ:
    WINDOW_SIZE: (1, 16)